name: On pull request

on:
  pull_request:
    branches: # PRs to the following branches will trigger the workflow
      - main
      - develop
    paths:
      - src/**

jobs:
  check-changes:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    outputs:
      src_changes: ${{ steps.is-normalize-changed.outputs.changes }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check file changes
        id: is-normalize-changed
        uses: dorny/paths-filter@v2
        with:
          filters: |
            normalize:
              - 'src/normalize/**'
            transform:
              - 'src/transform/**'

  lint-and-build:
    needs: check-changes
    strategy:
      matrix:
        lib: ${{ fromJSON(needs.check-changes.outputs.src_changes) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/${{ matrix.lib }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Installing Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry - ${{ matrix.lib }}
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv - ${{ matrix.lib }}
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies - ${{ matrix.lib }}
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install

      - name: Format - ${{ matrix.lib }}
        run: |
          poetry run black .

      - name: Lint - ${{ matrix.lib }}
        run: |
          poetry run flake8 --exclude=.venv . --ignore="E,W"

      - name: Run tests - ${{ matrix.lib }}
        run: |
          poetry run pytest