name: Publish on push

on:
  pull_request:
    branches: # PRs to the following branches will trigger the workflow
      - main
      - develop
    paths:
      - src/**

jobs:
  Quality-check:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    outputs:
      auto-version: ${{ steps.auto-version.outputs.version }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check file changes
        id: is-normalize-changed
        uses: dorny/paths-filter@v2
        with:
          filters: |
            normalize:
              - 'src/normalize/**'
            transform:
              - 'src/transform/**'

      - name: Install dependencies
        run: |
          make install-deps
          curl -sSL https://install.python-poetry.org | python -
          poetry --version

      - name: Run format
        run: |
          make fmt

      - name: Run linting
        run: |
          make lint

      # - name: Download latest auto
      #   run: |
      #     auto_download_url="$(curl -fsSL https://api.github.com/repos/intuit/auto/releases/latest | jq -r '.assets[] | select(.name == "auto-linux.gz") | .browser_download_url')"
      #     wget -O- "$auto_download_url" | gunzip > ~/auto
      #     chmod a+x ~/auto

      # - name: Check whether a release is due
      #   id: auto-version
      #   run: |
      #     version="$(~/auto version)"
      #     echo "::set-output name=version::$version"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create release
      #   run: |
      #     ~/auto shipit
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 